### ISSUE TITLE
Disk space alerts not working due to wrong metrics used

### ISSUE THREAD

**Issue by ybalt** [scylladb/scylla-monitoring#1282]
Download
https://github.com/scylladb/scylla-monitoring/archive/scylla-monitoring-3.5.tar.gz
unpack and run

Panel Name: - 
Dashboard Name: - 
Scylla-Monitoring Version: 3.5
Scylla-Version: 4.1

All alerts that calculate free disk space are not working, for example

```
alert: DiskFull
expr: node_filesystem_avail{mountpoint="/var/lib/scylla"}
  / node_filesystem_size{mountpoint="/var/lib/scylla"} * 100 < 25
for: 30s
labels:
  severity: "2"
annotations:
  description: '{{ $labels.instance }} has less than 25% free disk space.'
  summary: Instance {{ $labels.instance }} low disk space
```

the reason is a wrong metric name, there is no metric with name 'node_filesystem_avail' present on scylla prometheus, but
'node_filesystem_avail_bytes' is present.  The same with 'node_filesystem_size', it should be replaced with 'node_filesystem_size_bytes' to correct work.

This bug is very dangerous, as may result no free space on disk and cluster down without any notifications
