### ISSUE TITLE
Keeping receiving error log when query p95/p99 metric

### ISSUE THREAD

**Issue by codingcuisg** [scylladb/scylla-monitoring#1430]
Hi Team, 

We keep receiving error broken pipe issue when query p95/p99 metric, any suggestion to fix it?

prometheus:v2.18.1

![image](https://user-images.githubusercontent.com/33821205/121317847-3f78c700-c93d-11eb-9e5e-03fc1458fe77.png)

> level=error ts=2021-06-09T06:40:18.134Z caller=federate.go:192 component=web msg="federation failed" err="write tcp 172.17.0.3:9090->10.190.96.171:55764: write: broken pipe"
level=error ts=2021-06-09T06:40:33.322Z caller=federate.go:192 component=web msg="federation failed" err="write tcp 172.17.0.3:9090->10.190.96.171:55812: write: broken pipe"
level=error ts=2021-06-09T06:40:48.110Z caller=federate.go:192 component=web msg="federation failed" err="write tcp 172.17.0.3:9090->10.190.96.171:55864: write: broken pipe"
level=error ts=2021-06-09T06:41:04.319Z caller=federate.go:192 component=web msg="federation failed" err="write tcp 172.17.0.3:9090->10.190.96.171:55922: write: broken pipe"
level=error ts=2021-06-09T06:41:18.308Z caller=federate.go:192 component=web msg="federation failed" err="write tcp 172.17.0.3:9090->10.190.96.171:55972: write: broken pipe"

Thanks

**Comment by amnonh** [comment]
I wonder where the fedration msg is comming from, is there anything different in your setup? like multiple prometheus servers or proxy?

**Comment by codingcuisg** [comment]
Hi amnonh, we only have one prometheus server. this issue happened when the using wide time range, if 5mins, 30mins it's working fine, but if I choose 2days, the issue happened. Is it caused by fetching huge data then the request timeout? I tried to fetch it by prometheus(localhost:9090), fetching 2days data cost around 7seconds

**Comment by amnonh** [comment]
I believe the root cause is federation, I don't understand why you are using federation.
Grafana should read from the prometheus server directly, and it should read directly from Scylla.

Regardless I suggest to upgrade your prometheus server, there are many improvements in the newer releases

**Comment by codingcuisg** [comment]
the prometheus config pasted, could you help check anything would help?

**Comment by codingcuisg** [comment]
[Uploading config.txt…]()

**Comment by amnonh** [comment]
Can you check how your Grafana's prometheus-data source is configured?

**Comment by codingcuisg** [comment]
![image](https://user-images.githubusercontent.com/33821205/121512467-52ae9400-ca1c-11eb-99e1-427c6defb73c.png)
![image](https://user-images.githubusercontent.com/33821205/121512684-91444e80-ca1c-11eb-892a-276b1f74b7da.png)

There all running in docker within same ec2 instance

**Comment by amnonh** [comment]
maybe it's a red-hering, but the error message state that it's a federation error, but it seems that you are not using federation. The configuration file that you showed is a copy of the template configuration file that ship with Scylla, if you are not using the start-all.sh script you should atleast update the alertmanager address.

Did you copy the configuration from the prometheus server http://{ip}:9090/config or did you take it from the disk?

Regardless, I suggest that you upgrade your prometheus and grafana servers, newer versions are more stable with regards to OOM

**Comment by codingcuisg** [comment]
Thanks for checking, yeah, I am using start-all.sh, the config I copied from disk is the same as http://{ip}:9090/config.

I will consider upgrade upgrade prometheus and grafana version.

**Comment by codingcuisg** [comment]
> maybe it's a red-hering, but the error message state that it's a federation error, but it seems that you are not using federation. The configuration file that you showed is a copy of the template configuration file that ship with Scylla, if you are not using the start-all.sh script you should atleast update the alertmanager address.
> 
> Did you copy the configuration from the prometheus server http://{ip}:9090/config or did you take it from the disk?
> 
> Regardless, I suggest that you upgrade your prometheus and grafana servers, newer versions are more stable with regards to OOM

Hey @amnonh  I upgraded scylla monitoring to version 3.7.2 already. But it doesn't solve my issue. I still encountering same issue when trying to get p95/p99 metric for a long time range. Any idea?

**Comment by codingcuisg** [comment]
```
global:
  scrape_interval: 20s
  scrape_timeout: 15s
  evaluation_interval: 1m
  external_labels:
    monitor: scylla-monitor
alerting:
  alertmanagers:
  - scheme: http
    timeout: 10s
    api_version: v1
    static_configs:
    - targets:
      - 172.17.0.2:9093
rule_files:
- /etc/prometheus/prometheus.rules.yml
scrape_configs:
- job_name: scylla
  honor_timestamps: true
  scrape_interval: 20s
  scrape_timeout: 15s
  metrics_path: /metrics
  scheme: http
  relabel_configs:
  - source_labels: [__address__]
    separator: ;
    regex: ([^:]+)
    target_label: __address__
    replacement: ${1}:9180
    action: replace
  - source_labels: [__address__]
    separator: ;
    regex: (.*):.+
    target_label: instance
    replacement: ${1}
    action: replace
  metric_relabel_configs:
  - source_labels: [version]
    separator: ;
    regex: (.+)
    target_label: CPU
    replacement: cpu
    action: replace
  - source_labels: [version]
    separator: ;
    regex: (.+)
    target_label: CQL
    replacement: cql
    action: replace
  - source_labels: [version]
    separator: ;
    regex: (.+)
    target_label: OS
    replacement: os
    action: replace
  - source_labels: [version]
    separator: ;
    regex: (.+)
    target_label: IO
    replacement: io
    action: replace
  - source_labels: [version]
    separator: ;
    regex: (.+)
    target_label: Errors
    replacement: errors
    action: replace
  - separator: ;
    regex: help|exported_instance
    replacement: $1
    action: labeldrop
  - source_labels: [version]
    separator: ;
    regex: ([0-9]+\.[0-9]+)(\.?[0-9]*).*
    target_label: svr
    replacement: $1$2
    action: replace
  file_sd_configs:
  - files:
    - /etc/scylla.d/prometheus/scylla_servers.yml
    refresh_interval: 5m
- job_name: node_exporter
  honor_timestamps: true
  scrape_interval: 1m
  scrape_timeout: 20s
  metrics_path: /metrics
  scheme: http
  relabel_configs:
  - source_labels: [__address__]
    separator: ;
    regex: (.*):\d+
    target_label: instance
    replacement: ${1}
    action: replace
  - source_labels: [__address__]
    separator: ;
    regex: ([^:]+)
    target_label: instance
    replacement: ${1}
    action: replace
  - source_labels: [instance]
    separator: ;
    regex: (.*)
    target_label: __address__
    replacement: ${1}:9100
    action: replace
  file_sd_configs:
  - files:
    - /etc/scylla.d/prometheus/node_exporter_servers.yml
    refresh_interval: 5m
- job_name: manager_agent
  honor_timestamps: true
  scrape_interval: 20s
  scrape_timeout: 15s
  metrics_path: /metrics
  scheme: http
  relabel_configs:
  - source_labels: [__address__]
    separator: ;
    regex: (.*):\d+
    target_label: instance
    replacement: ${1}
    action: replace
  - source_labels: [__address__]
    separator: ;
    regex: ([^:]+)
    target_label: instance
    replacement: ${1}
    action: replace
  - source_labels: [instance]
    separator: ;
    regex: (.*)
    target_label: __address__
    replacement: ${1}:56090
    action: replace
  file_sd_configs:
  - files:
    - /etc/scylla.d/prometheus/scylla_servers.yml
    refresh_interval: 5m
- job_name: manager_agent1
  honor_timestamps: true
  scrape_interval: 20s
  scrape_timeout: 15s
  metrics_path: /metrics
  scheme: http
  relabel_configs:
  - source_labels: [__address__]
    separator: ;
    regex: (.*):\d+
    target_label: instance
    replacement: ${1}
    action: replace
  - source_labels: [__address__]
    separator: ;
    regex: ([^:]+)
    target_label: instance
    replacement: ${1}
    action: replace
  - source_labels: [instance]
    separator: ;
    regex: (.*)
    target_label: __address__
    replacement: ${1}:5090
    action: replace
  file_sd_configs:
  - files:
    - /etc/scylla.d/prometheus/scylla_servers.yml
    refresh_interval: 5m
- job_name: scylla_manager
  honor_timestamps: true
  scrape_interval: 20s
  scrape_timeout: 15s
  metrics_path: /metrics
  scheme: http
  metric_relabel_configs:
  - source_labels: [host]
    separator: ;
    regex: (.*)
    target_label: instance
    replacement: $1
    action: replace
  file_sd_configs:
  - files:
    - /etc/scylla.d/prometheus/scylla_manager_servers.yml
    refresh_interval: 5m
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 5s
  scrape_timeout: 5s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090
```
