### ISSUE TITLE
Cannot monitor nodes over IPv6

### ISSUE THREAD

**Issue by Fornax96** [scylladb/scylla-monitoring#1621]
*Installation details*
Panel Name: Unreachable nodes
Dashboard Name: General / Overview
Scylla-Monitoring Version: master
Scylla-Version: 4.5.1

My Scylla cluster is running completely on IPv6, each node has a domain name with an AAAA record. When I removed the A records the monitoring stopped working. I followed the instructions on this page to no avail: https://docs.scylladb.com/operating-scylla/monitoring/3.1/monitoring-stack/

The cluster itself is operating perfectly according to nodetool status, but scylla-monitoring tells me all my nodes are unreachable. I have tried both setting IP addresses and hostnames in `prometheus/scylla_servers.yml` but neither works. I have verified that node_exporter is running on IPv6 on every node. According to `netstat -tulpn` it's listening on `[::]:9100` which is publicly accessible.

![image](https://user-images.githubusercontent.com/1247928/146039344-2c3fe28f-8486-43b2-aa8c-369961e33d99.png)

**Comment by amnonh** [comment]
@Fornax96 can you please include the content of `prometheus/scylla_servers.yml`

Also, can you verify that a `curl http://[ipv6]:9180/metrics` command works from the monitoring server to the scylla server

**Comment by Fornax96** [comment]
```
- targets:
  - de3.scylla.pixeldrain.com:9180
  labels:
    cluster: pixeldrain
    dc: eu-de
- targets:
  - us-west1.scylla.pixeldrain.com:9180
  - us-west2.scylla.pixeldrain.com:9180
  - us-west3.scylla.pixeldrain.com:9180
  labels:
    cluster: pixeldrain
    dc: us-west
- targets:
  - fi3.scylla.pixeldrain.com:9180
  labels:
    cluster: pixeldrain
    dc: fi
```

I get a large data dump from the curl call, so that seems to work fine. `curl http://de3.scylla.pixeldrain.com:9180/metrics`
