### ISSUE TITLE
Latencies percentiles aggregations may give misleading results

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla-monitoring#1886]
*Installation details*
Panel Name: latenices aggregations
Dashboard Name: Detailed, Overview, Advanced
Scylla-Monitoring Version: 4.1.0
Scylla-Version: irrelevant

*Description*
Our percentiles macros are averaging Ps (e.g. P99) across shads/nodes/DCs.
This can only give a result close to the real P99 if each separate per-shard Ps are close to one another.

However if a tail latency on some shards is significantly higher than on others and if higher Ps tail latency of all shards is high this will return a much lower value than the real one.

In general, a much more realistic approximation for a P in the whole system given Ps on separate shards in a `max` function. 
It will approximate the real value from the top and it may get scary but when we look at Ps we want to see the ugly truth instead of a pretty picture. ;)

**Comment by vladzcloudius** [comment]
@avikivity @fee-mendes FYI

**Comment by amnonh** [comment]
In fact, we calculate the P95, P99 on each level seperately, i.e.
calculate at a shard level, at a node level at a DC level and at a cluster level.

For example, to answer the question what is the P99 of a cluster, we calculate a histogram of all latencies from all shards and get the P99 from that histogram.

**Comment by isburmistrov** [comment]
I'm confused @amnonh. Is this expression that's being ultimately used for e.g. instance latency?

`histogram_quantile(0.99, sum(rate(scylla_storage_proxy_coordinator_read_latency_bucket{scheduling_group_name!~"atexit|gossip|mem_compaction|memtable|streaming|background_reclaim|compaction|main|memtable_to_cache"}[60s])) by (cluster, dc, instance, scheduling_group_name, le))`

**Comment by amnonh** [comment]
Latencies calculations are done with recording rules, we have one for each level for example we have `rlatencyp95` rule for shard, for node, for dc and for cluster.
(we actually have two for each so we can mark to datadog what to scrap)

**Comment by isburmistrov** [comment]
Can you share what happens when we calculate e.g. per-instance latency?

> For example, to answer the question what is the P99 of a cluster, we calculate a histogram of all latencies from all shards and get the P99 from that histogram.

Because this is not clear what means exactly.

**Comment by amnonh** [comment]
For a shard view we are calclating:
```
  - record: rlatencyp95
    expr: histogram_quantile(0.95, sum(rate(scylla_storage_proxy_coordinator_read_latency_bucket{shard=~".+", scheduling_group_name=~"atexit|gossip|mem_compaction|memtable|streaming|background_reclaim|compaction|main|memtable_to_cache"}[60s])) by (cluster, dc, instance, shard, scheduling_group_name, le))
    labels:
      by: "instance,shard"
```

So we are calculating the latency for each of the shards

**Comment by amnonh** [comment]
I tend to close as not a bug, but maybe there's somthing that I am missing.

Just to conclude, let's talk about p99 write latencies of the cluster.
if you look at all the writes in the last minute, let's say there where 1000 writes.
you order all 1000 in a descending order, the value at position 10, is your p99.

But you need to take all queries from all shards and nodes to calculat the cluster p99

**Comment by vladzcloudius** [comment]
> I tend to close as not a bug, but maybe there's somthing that I am missing.
> 
> Just to conclude, let's talk about p99 write latencies of the cluster. if you look at all the writes in the last minute, let's say there where 1000 writes. you order all 1000 in a descending order, the value at position 10, is your p99.
> 
> But you need to take all queries from all shards and nodes to calculat the cluster p99

That's correct, @amnonh. And since you don't know how the sorting is going to be node-wide and cluster-wide you hit the problem I've described above by averaging.

**Comment by vladzcloudius** [comment]
> In fact, we calculate the P95, P99 on each level seperately, i.e. calculate at a shard level, at a node level at a DC level and at a cluster level.
> 
> For example, to answer the question what is the P99 of a cluster, we calculate a histogram of all latencies from all shards and get the P99 from that histogram.

Do we? I strongly doubt that, @amnonh.
You get histograms for shard-level only from Scylla.
And from what I saw what you do next in Prometheus - you average:

```
"targets":[
               {
                  "expr":"avg(rlatencyp99{by=\"cluster\", cluster=~\"$cluster|^$\",scheduling_group_name!=\"streaming\"}>0)",
                  "intervalFactor":1,
                  "legendFormat":"",
                  "refId":"A",
                  "instant":true,
                  "step":4
               }
            ],
```

**Comment by vladzcloudius** [comment]
> For a shard view we are calclating:
> 
> ```
>   - record: rlatencyp95
>     expr: histogram_quantile(0.95, sum(rate(scylla_storage_proxy_coordinator_read_latency_bucket{shard=~".+", scheduling_group_name=~"atexit|gossip|mem_compaction|memtable|streaming|background_reclaim|compaction|main|memtable_to_cache"}[60s])) by (cluster, dc, instance, shard, scheduling_group_name, le))
>     labels:
>       by: "instance,shard"
> ```
> 
> So we are calculating the latency for each of the shards

This doesn't make sense: based on the expression for `instance` for instance we were supposed to see the P99 close to the "sum" on P99s from shard:

```
  - record: rlatencyp99
    expr: histogram_quantile(0.99, sum(rate(scylla_storage_proxy_coordinator_read_latency_bucket{scheduling_group_name!~"atexit|gossip|mem_compaction|memtable|streaming|background_reclaim|compaction|main|memtable_to_cache"}[60s])) by (cluster, dc, instance, scheduling_group_name, le))
    labels:
      by: "instance"
      level: "1"
```

But this is not what we see. We don't even see a proper bucketing on the per instance level too:

![image](https://user-images.githubusercontent.com/6103981/217303449-23c28d66-2d3e-4058-ba1d-427e249cc0c9.png)
![image](https://user-images.githubusercontent.com/6103981/217303492-1f9cbed4-3cbb-4c03-87a2-735c1180f6eb.png)
![image](https://user-images.githubusercontent.com/6103981/217303518-1781384d-e312-49be-bd21-2797c5b6eb2c.png)

As you can see the system has 44 shards, so I would expect that the cross shard P99 would be as the highest or at worst the second highest shard.

However the aggregated value looks like an average.

@amnonh comments?
