### ISSUE TITLE
Gaps in recording rules graphs in clusters with many cores

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla-monitoring#1935]
Scylla Monitoring 4.3 uses shorter ```evaluation_interval:``` in a cluster with many cores it causes gaps in the recording rules

**Comment by amnonh** [comment]
Work around:
1. Use a longer evaluation interval. Edit ```prometheus/prometheus.yml.template``` and set ```evaluation_interval: 60```.
2. If you are not using cdc and cas, you can remove those metrics. Edit ```prometheus/prometheus.yml.template```
Under ```job_name: scylla``` find the ```  metric_relabel_configs:``` part and add an entry to it.

```
  metric_relabel_configs:
    - source_labels: [__name__]
      regex: '(.*_cdc_.*|.*_cas.*)'
      action: drop
```

After changing the file you will need to call ```kill-all.sh``` and ```start-all.sh``` for the changes to take effect.
