### ISSUE TITLE
[Regression]: prometheus/prom_rules/prometheus.rules.yml: severities are inverted

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla-monitoring#2029]
*Installation details*
Scylla-Monitoring Version: 4.4.2

*Description*
Patch 2e3d0c7280599f2d09b9eea102f522defdd05db6

```
commit 2e3d0c7280599f2d09b9eea102f522defdd05db6
Author: Amnon Heiman <amnon@scylladb.com>
Date:   Wed Mar 15 10:22:20 2023 +0200

    prometheus.rules.yml: Use severity as string instead of numbers
```

set wrong severities values.

For example he set "info" severity to a "DiskFull with less than 15% free" alert and "error" for a "DiskFull 35% disk left"

```
  - alert: DiskFull
    expr: node_filesystem_avail_bytes{mountpoint="/var/lib/scylla"} / node_filesystem_size_bytes{mountpoint="/var/lib/scylla"}
      * 100 < 35
    for: 30s
    labels:
      severity: "error"
    annotations:
      description: '{{ $labels.instance }} has less than 35% free disk space.'
      summary: Instance {{ $labels.instance }} low disk space
  - alert: DiskFull
    expr: node_filesystem_avail_bytes{mountpoint="/var/lib/scylla"} / node_filesystem_size_bytes{mountpoint="/var/lib/scylla"}
      * 100 < 25
    for: 30s
    labels:
      severity: "warn"
    annotations:
      description: '{{ $labels.instance }} has less than 25% free disk space.'
      summary: Instance {{ $labels.instance }} low disk space
  - alert: DiskFull
    expr: node_filesystem_avail_bytes{mountpoint="/var/lib/scylla"} / node_filesystem_size_bytes{mountpoint="/var/lib/scylla"}
      * 100 < 15
    for: 30s
    labels:
      severity: "info"
    annotations:
      description: '{{ $labels.instance }} has less than 15% free disk space.'
      summary: Instance {{ $labels.instance }} low disk space
```
