### ISSUE TITLE
Not possible to run two monitoring stacks side-by-side

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla-monitoring#2164]
I have two runs I want to compare. But I can't start two stacks, because the container names are hardcoded everywhere. I can't even start one stack with the two runs, because one can import only one prometheus dump.

**Comment by amnonh** [comment]
you can, to do that you need to specify the different ports, the ports numbers will be part of the names.
This is the recommended way of doing a safe upgrade:
https://monitoring.docs.scylladb.com/stable/upgrade/upgrade-guide-from-monitoring-4.x-to-monitoring-4.y.html#validate-the-version-installed-correctly

Let me know tf that does not answer the question, if it does, please close

**Comment by tzach** [comment]
Another idea, is to collect both clusters metrics to the same monitoring stack, but to two different "clusters" ot "DCs"


```
# An example with a single cluster and two DC
- targets:
       - 172.17.0.1:9180
       - 172.17.0.2:9180
       - 172.17.0.3:9180
  labels:
       cluster: cluster1
       dc: dc1
- targets:
       - 172.16.0.1:9180
       - 172.16.0.2:9180
       - 172.16.0.3:9180
  labels:
       cluster: cluster2
       dc: dc1
```
