### ISSUE TITLE
node_exporter_servers.yml example not consistent 

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-monitoring#396]
node_exporter_servers.yml example not consistent, mixing port numbers (9100, 9180)

```
# List end points with node exporter

- targets:
  - '172.17.0.2:9100'
  labels:
       cluster: cluster1
       dc: dc1
- targets:
       - 172.17.0.3:9180
  labels:
       cluster: cluster1
       dc: dc2
```
