### ISSUE TITLE
Empty I/O dashboard from last upgrade

### ISSUE THREAD

**Issue by fggarcia** [scylladb/scylla-monitoring#492]
Since upgrade from 3.0.1 to 3.0.2 in Disk Activity from Scylla Per-Server Disk I/O (master & 3.0 version)

All metrics values disappeared

![image](https://user-images.githubusercontent.com/1306596/52302357-b667b480-296b-11e9-8a54-b54278eb2210.png)

**Comment by amnonh** [comment]
All those metrics come from node_exporter, could it be that you didn't start it for some reason?

**Comment by fggarcia** [comment]
Hi @amnonh 
Graphs, those are below, show metrics. So, this confuse me about node exporter process

PD: some other metric graphs from same view
![image](https://user-images.githubusercontent.com/1306596/52305545-1cf0d080-2974-11e9-8de1-f51046a8e2a5.png)

**Comment by fggarcia** [comment]
Sorry @amnonh 
i see node_exporter service on systemd 
flag provided but not defined: -collector.interrupts

i will report in scylla project

**Comment by amnonh** [comment]
if that is the case, it means you are running node_exporter 0.14 instead of
0.17

**Comment by fggarcia** [comment]
Hi @amnonh 

Now that i upgrade node_exporter to 0.17

```
node_exporter --version
node_exporter, version 0.17.0 (branch: HEAD, revision: f6f6194a436b9a63d0439abc585c76b19a206b21)
  build user:       root@322511e06ced
  build date:       20181130-15:51:33
  go version:       go1.11.2

```

![image](https://user-images.githubusercontent.com/1306596/52458385-d058f100-2b3d-11e9-8dad-b23a53c9e753.png)

I saw that you use node_disk_bytes_read to extract disk name.....but:

old instance (0.14 node_exporter)
```
node_exporter --version
node_exporter, version 0.14.0 (branch: master, revision: 840ba5dcc71a084a3bc63cb6063003c1f94435a6)
  build user:       root@bb6d0678e7f3
  build date:       20170321-12:12:54
  go version:       go1.7.5
```
and extract metrics:

```
curl -X GET 'http://localhost:9100/metrics' | grep 'node_disk_bytes_read'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0# HELP node_disk_bytes_read The total number of bytes read successfully.
# TYPE node_disk_bytes_read counter
node_disk_bytes_read{device="nvme0n1"} 7.327791104e+09
node_disk_bytes_read{device="nvme1n1"} 1.09974226105344e+14
100 95153  100 95153    0     0  14.3M      0 --:--:-- --:--:-- --:--:-- 15.1M
```

instance with new version of node_exporter:

```
node_exporter --version
node_exporter, version 0.17.0 (branch: HEAD, revision: f6f6194a436b9a63d0439abc585c76b19a206b21)
  build user:       root@322511e06ced
  build date:       20181130-15:51:33
  go version:       go1.11.2
```
```
curl -X GET 'http://localhost:9100/metrics' | grep 'node_disk_bytes_read'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 55886    0 55886    0     0  4168k      0 --:--:-- --:--:-- --:--:-- 4548k
```

**Comment by amnonh** [comment]
You are right, to be backwards compatible we configure prometheus to change
the metrics nanes so the dashboards would continue to work.

You can learn about it more in the prometheus configuration part here:
https://github.com/scylladb/scylla-grafana-monitoring/blob/master/README.md

**Comment by fggarcia** [comment]
Hi @amnonh 
you are mention to section "Using your own Prometheus server node_exporter specifc configuration"

where should this configuration stay? On scylla server or scylla-grafana-monitoring server(we use docker image)?

If this configuration should stay in scylla-server, why do scylla install not create this file?

Thanks you for your help

**Comment by amnonh** [comment]
It's part of prometheus configuration, part of the manager configuration.

If you are using the docker solution, it will be configure for you, so you
don't need to do anything

**Comment by fggarcia** [comment]
Yes, sorry it was a stupid question :P 

I find that configuration in prometheus.yml.template

I upgrade to node_exporter 0.17, but i still don't see that metrics in Scylla-Per-Server Disk

![image](https://user-images.githubusercontent.com/1306596/52484499-3fadff80-2b95-11e9-94da-cb19c1c7d9d2.png)
![image](https://user-images.githubusercontent.com/1306596/52484565-6409dc00-2b95-11e9-8382-09cd11f0cffa.png)

For example, our disk name is vda. Not exist in disk label options

**Comment by amnonh** [comment]
@fggarcia First I'm happy that it's working better already.

Second, to understand the source of the problem why you don't see the relevant label, can you please open the prometheus dashboard:
http://{ip}:9090 (for example if you are checking it locally it will be http://127.0.0.1:9090)

And check what the value of: 
node_disk_bytes_read

It should return all values from all hosts.

**Comment by fggarcia** [comment]
There are only metrics from instances was not upgraded to node-exporter 0.17
![image](https://user-images.githubusercontent.com/1306596/52493993-945c7500-2bab-11e9-9282-a35cb8888523.png)

**Comment by amnonh** [comment]
it's either that prometheus cannot read from those nodes, or the name change in the configuration is not working propertly.

To check the first option check the targets tab in prometheus:
http://{ip}:9090/targets (where ip is the ip address).

make sure that all the node_exporter are up, if they are not, check what is the error code.

also, make sure that you are running the latest monitoring version.

**Comment by fggarcia** [comment]
Migrate all servers to node-exporter 0.17

![image](https://user-images.githubusercontent.com/1306596/52506801-794f2c80-2bce-11e9-9d4e-3b9351640b1c.png)


But already happen that not show disks monitor

![image](https://user-images.githubusercontent.com/1306596/52506888-bb786e00-2bce-11e9-8256-3cb75e131e4e.png)

**Comment by fggarcia** [comment]
update:

```
docker exec -it aprom cat /etc/prometheus/prometheus.yml
global:
  scrape_interval: 5s # By default, scrape targets every 5 second.
  scrape_timeout: 4s # Timeout before trying to scape a target again

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'scylla-monitor'
rule_files:
  - /etc/prometheus/prometheus.rules.yml
    #
# Alerting specifies settings related to the Alertmanager.
alerting:
        #  alert_relabel_configs:
        #    [ - <relabel_config> ... ]
  alertmanagers:
  - static_configs:
    - targets:
        - 172.17.0.2:9093

scrape_configs:
- job_name: scylla
  honor_labels: false
  file_sd_configs:
    - files:
      - /etc/scylla.d/prometheus/scylla_servers.yml
  relabel_configs:
    - source_labels: [__address__]
      regex:  '(.*):.+'
      target_label: instance
      replacement: '${1}'

- job_name: node_exporter
  honor_labels: false
  file_sd_configs:
    - files:
      - /etc/scylla.d/prometheus/node_exporter_servers.yml
  relabel_configs:
    - source_labels: [__address__]
      regex:  '(.*):\d+'
      target_label: instance
      replacement: '${1}'
    - source_labels: [__address__]
      regex:  '(.*):\d+'
      target_label: __address__
      replacement: '${1}:9100'
    - source_labels: [__name__]
      regex:  'node_disk_read_bytes_total'
      target_label: __name__
      replacement: 'node_disk_bytes_read'
    - source_labels: [__name__]
      regex:  'node_disk_written_bytes_total'
      target_label: __name__
      replacement: 'node_disk_bytes_written'
    - source_labels: [__name__]
      regex:  'node_disk_reads_completed_total'
      target_label: __name__
      replacement: 'node_disk_reads_completed'
    - source_labels: [__name__]
      regex:  'node_disk_writes_completed_total'
      target_label: __name__
      replacement: 'node_disk_writes_completed'
    - source_labels: [__name__]
      regex:  'node_filesystem_avail_bytes'
      target_label: __name__
      replacement: 'node_filesystem_avail'
    - source_labels: [__name__]
      regex:  'node_network_receive_bytes_total'
      target_label: __name__
      replacement: 'node_network_receive_bytes'
    - source_labels: [__name__]
      regex:  'node_network_receive_packets_total'
      target_label: __name__
      replacement: 'node_network_receive_packets'
    - source_labels: [__name__]
      regex:  'node_network_transmit_bytes_total'
      target_label: __name__
      replacement: 'node_network_transmit_bytes'
    - source_labels: [__name__]
      regex:  'node_network_transmit_packets_total'
      target_label: __name__
      replacement: 'node_network_transmit_packets'
    - source_labels: [__name__]
      regex:  'node_filesystem_size_bytes'
      target_label: __name__
      replacement: 'node_filesystem_size'

- job_name: scylla_manager
  honor_labels: false
  file_sd_configs:
    - files:
      - /etc/scylla.d/prometheus/scylla_manager_servers.yml
  metric_relabel_configs:
    - source_labels: [host]
      target_label: instance

- job_name: 'prometheus'
  # Override the global default and scrape targets from this job every 5 seconds.
  scrape_interval: 5s
  static_configs:
    - targets:
      - localhost:9090
```

For example:
**node_disk_read_bytes_total**
![image](https://user-images.githubusercontent.com/1306596/52516085-b08c0080-2c03-11e9-979d-47c43d4f1f37.png)

but
**node_disk_bytes_read**
![image](https://user-images.githubusercontent.com/1306596/52516096-daddbe00-2c03-11e9-8951-5719576dd62b.png)

I don't know why the job not replace the original metrics.

If i replace manually metrics in dashboard, the dashboard works correctly.

Any idea?

PD: I delete/remove original images, and download docker images again.
