### ISSUE TITLE
Prometheus.rules.yaml NoCQL rule looks for `cql_status` metric, but metric name in Manager is `scylla_manager_healthcheck_cql_status`

### ISSUE THREAD

**Issue by tomer-sandler** [scylladb/scylla-monitoring#550]
**prometheus/prometheus.rules.yml**

```
groups:
- name: scylla.rules
  rules:
  - alert: InstanceDown
    expr: up == 0
    for: 30s
    labels:
      severity: "2"
    annotations:
      description: ' has been down for more than 30 seconds.'
      summary: Instance down
  - alert: DiskFull
    expr: node_filesystem_avail{mountpoint="/var/lib/scylla"} / node_filesystem_size{mountpoint="/var/lib/scylla"}
      * 100 < 25
    for: 30s
    labels:
      severity: "2"
    annotations:
      description: ' has less than 25% free disk space.'
      summary: Instance low disk space
  - alert: DiskFull
    expr: node_filesystem_avail{mountpoint="/var/lib/scylla"} / node_filesystem_size{mountpoint="/var/lib/scylla"}
      * 100 < 10
    for: 30s
    labels:
      severity: "3"
    annotations:
      description: ' has less than 10% free disk space.'
      summary: Instance low disk space
  - alert: DiskFull
    expr: node_filesystem_avail{mountpoint="/var/lib/scylla"} / node_filesystem_size{mountpoint="/var/lib/scylla"}
      * 100 < 1
    for: 30s
    labels:
      severity: "4"
    annotations:
      description: ' has less than 1% free disk space.'
      summary: Instance low disk space
  - alert: NoCql
    expr: cql_status == -1
    for: 30s
    labels:
      severity: "2"
    annotations:
      description: ' has denied cql connection for more than 30 seconds.'
      summary: Instance no cql connection
```

```
$ curl -s 127.0.0.1:56090/metrics | grep cql_status
# HELP scylla_manager_healthcheck_cql_status Host native port status
# TYPE scylla_manager_healthcheck_cql_status gauge
scylla_manager_healthcheck_cql_status{cluster="prod-cluster",host="10.118.0.2"} 1
scylla_manager_healthcheck_cql_status{cluster="prod-cluster",host="10.118.0.3"} 1
scylla_manager_healthcheck_cql_status{cluster="prod-cluster",host="10.118.0.4"} 1
scylla_manager_healthcheck_cql_status{cluster="prod-cluster",host="10.118.0.5"} 1
scylla_manager_healthcheck_cql_status{cluster="prod-cluster",host="10.118.0.6"} 1
scylla_manager_healthcheck_cql_status{cluster="prod-cluster",host="10.118.0.7"} 1
```
