### ISSUE TITLE
Total available storage is incorrect in Grafana

### ISSUE THREAD

**Issue by arita37** [scylladb/scylla-monitoring#980]
scylla-version=3.3
monitoring-version=3.3

nodetool status shows 250 Gb
whereas grafana shows 20mb....

**Comment by amnonh** [comment]
Note that in the dashboard, the display is per a specific partition, are you sure it's inaccurate?

**Comment by arita37** [comment]
It does not show the amount of data used by
scylla on the disk.

This allows to setup trigger when disk is reaching limit...

**Comment by amnonh** [comment]
We are setting triggers when the disk partition is reaching its limit.

For example, see `prometheus/prometheus.rule.yml` that assumes the data is in `/var/lib/scylla` partition.

```
  - alert: DiskFull
    expr: node_filesystem_avail{mountpoint="/var/lib/scylla"} / node_filesystem_size{mountpoint="/var/lib/scylla"}
      * 100 < 25
    for: 30s
    labels:
      severity: "2"
    annotations:
      description: '{{ $labels.instance }} has less than 25% free disk space.'
      summary: Instance {{ $labels.instance }} low disk space

```
