### ISSUE TITLE
Make sure monitoring works with podman

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla-monitoring#994]
podman replaces docker in some installation, we should support it as well

**Comment by gleb-cloudius** [comment]
It starts, but generated grafana/provisioning/datasources/datasource.yaml is broken:

```
# config file version
apiVersion: 1
datasources:
- name: prometheus
  type: prometheus
  url: http://:9090
  access: proxy
  basicAuth: false

- name: alertmanager
  type: camptocamp-prometheus-alertmanager-datasource
  orgId: 1
  typeLogoUrl: public/img/icn-datasource.svg
  access: proxy
  url: http://:9093
  password:
  user:
  database:
  basicAuth:
  isDefault:
  jsonData:
    severity_critical: '4'
    severity_high: '3'
    severity_warning: '2'
    severity_info: '1'

```
